---
title: "Boulder Open Space and Mountain Parks"
subtitle: "Figures and statistics"
author: "Hannah Miller"
output:
  html_document: 
    df_print: paged
    toc: yes
    toc_depth: 2
    toc_float: true
    code_folding: show
editor_options:
  chunk_output_type: inline
source: source.dropbox(https://www.dropbox.com/s/1e5t6l7xt4emgwp/N_cycling.csv?dl=0))
---
```{r, include=FALSE}
#load necessary packages
library(readxl)
library(tidyverse)
library(ggplot2)
library(nortest)
library(Rmisc)
library(gt)
library(plotly)
library(gridExtra)
library(FSA)
library(ggpubr)
```
# Nitrogen cycling figures 
```{r plotting graphs, echo=FALSE, warning = FALSE}
#Load N_cycling excel file
N_cycling <- read.csv("~/Dropbox/Boulder_OSMP_TOG/Data/N_cycling.csv")

#plot net mineralization per site for all data
p1 <- ggplot(data = N_cycling, mapping = aes(x = Site, y = Net_Mineralization, fill = Invasion, label=Field_ID)) + 
   geom_boxplot() + 
   ggtitle("All data") + 
   theme(plot.title = element_text(hjust = 0.5)) + 
   ylab("Net Mineralization (ug/g/day)") + 
   scale_y_continuous(limits = c(-1.75, 1))


#plot net nitrification per site for all data
p2 <- ggplot(data = N_cycling, mapping = aes(x = Site, y = Net_Nitrification, fill = Invasion, label=Field_ID)) + 
   geom_boxplot() + 
   ggtitle("All data") + 
   theme(plot.title = element_text(hjust = 0.5)) + 
   ylab("Net Nitrification (ug/g/day)") + 
   scale_y_continuous(limits = c(-0.75, 1.5))

#plot net mineralization per site invaded versus uninvaded for Fall 2019
p3 <- ggplot(data = N_cycling, mapping = aes(x = Site, y = Net_Mineralization, fill = Invasion, label=Field_ID)) + 
   geom_boxplot(data=subset(N_cycling, Season=="Fall19")) + 
   ggtitle("Fall 2019") + 
   theme(plot.title = element_text(hjust = 0.5)) + 
   ylab("Net Mineralization (ug/g/day)") + 
   scale_y_continuous(limits = c(-1.75, 1))

#plot net mineralization per site invaded versus uninvaded for Spring 2020
p4 <- ggplot(data = N_cycling, mapping = aes(x = Site, y = Net_Mineralization, fill = Invasion,label=Field_ID)) + 
   geom_boxplot(data=subset(N_cycling, Season=="Spring20", position = "dodge")) + 
   ggtitle("Spring 2020") + 
   theme(plot.title = element_text(hjust = 0.5)) + 
   ylab("Net Mineralization (ug/g/day)") + 
   scale_y_continuous(limits = c(-1.75, 1))

#plot net nitrification per site invaded versus uninvaded for Fall 2019
p5 <- ggplot(data = N_cycling, mapping = aes(x = Site, y = Net_Nitrification, fill = Invasion, label=Field_ID)) + 
   geom_boxplot(data=subset(N_cycling, Season=="Fall19")) + 
   ggtitle("Fall 2019") + 
   theme(plot.title = element_text(hjust = 0.5)) + 
   ylab("Net Nitrification (ug/g/day)") + 
   scale_y_continuous(limits = c(-1.75, 1))

#plot net nitrification per site invaded versus uninvaded for spring 2020
p6 <- ggplot(data = N_cycling, mapping = aes(x = Site, y = Net_Nitrification, fill = Invasion, label=Field_ID)) + 
   geom_boxplot(data=subset(N_cycling, Season=="Spring20")) + 
   ggtitle("Spring 2020") + 
   theme(plot.title = element_text(hjust = 0.5)) + 
   ylab("Net Nitrification (ug/g/day)") + 
   scale_y_continuous(limits = c(-1.75, 1))

#plot net mineralization versus invasion for all sites combined
p7 <- ggplot(data = N_cycling, mapping = aes(x = Invasion, y = Net_Mineralization)) + 
   geom_boxplot() + ggtitle("All data") + 
   theme(plot.title = element_text(hjust = 0.5)) + 
   ylab("Net Mineralization (ug/g/day)") + 
   scale_y_continuous(limits = c(-1.75, 1))

#plot net nitrification versus invasion for all sites combined
p8 <- ggplot(data = N_cycling, mapping = aes(x = Invasion, y = Net_Nitrification)) + 
   geom_boxplot() + ggtitle("All data") + 
   theme(plot.title = element_text(hjust = 0.5)) + 
   ylab("Net Nitrification (ug/g/day)") + 
   scale_y_continuous(limits = c(-1.75, 1))

#plot net mineralization versus invasion for all sites combined Fall 2019
p9 <- ggplot(data = N_cycling, mapping = aes(x = Invasion, y = Net_Mineralization)) + 
   geom_boxplot(data=subset(N_cycling, Season=="Fall19")) + 
   ggtitle("Fall 2019") + 
   theme(plot.title = element_text(hjust = 0.5)) + 
   ylab("Net Mineralization (ug/g/day)") + 
   scale_y_continuous(limits = c(-1.75, 1))

#plot net mineralization versus invasion for all sites combined Spring 2020
p10 <- ggplot(data = N_cycling, mapping = aes(x = Invasion, y = Net_Mineralization)) + 
   geom_boxplot(data=subset(N_cycling, Season=="Spring20")) + 
   ggtitle("Spring 2020") + 
   theme(plot.title = element_text(hjust = 0.5)) + 
   ylab("Net Mineralization (ug/g/day)") + 
   scale_y_continuous(limits = c(-1.75, 1))

#plot net nitrification versus invasion for all sites combined Fall 2019
p11 <- ggplot(data = N_cycling, mapping = aes(x = Invasion, y = Net_Nitrification)) + 
   geom_boxplot(data=subset(N_cycling, Season=="Fall19")) + 
   ggtitle("Fall 2019") + 
   theme(plot.title = element_text(hjust = 0.5)) + 
   ylab("Net Nitrification (ug/g/day)") + 
   scale_y_continuous(limits = c(-1.75, 1))

#plot net nitrification versus invasion for all sites combined Spring 2020
p12 <- ggplot(data = N_cycling, mapping = aes(x = Invasion, y = Net_Nitrification)) + 
   geom_boxplot(data=subset(N_cycling, Season=="Spring20")) + 
   ggtitle("Spring 2020") + theme(plot.title = element_text(hjust = 0.5)) + 
   ylab("Net Nitrification (ug/g/day)") + 
   scale_y_continuous(limits = c(-1.75, 1))


#p1 <- ggplotly(p1) %>% 
   #layout(boxmode = "group")
#p2 <- ggplotly(p2) %>% 
   #layout(boxmode = "group")
#p3 <- ggplotly(p3) %>% 
   #layout(boxmode = "group")
#p4 <- ggplotly(p4) %>% 
   #layout(boxmode = "group")
#p5 <- ggplotly(p5) %>% 
   #layout(boxmode = "group")
#p6 <- ggplotly(p6) %>% 
   #layout(boxmode = "group")
#p7 <- ggplotly(p7) %>% 
   #layout(boxmode = "group")
#p8 <- ggplotly(p8) %>% 
   #layout(boxmode = "group")
#p9 <- ggplotly(p9) %>% 
   #layout(boxmode = "group")
#p10 <- ggplotly(p10) %>% 
   #layout(boxmode = "group")
#p11 <- ggplotly(p11) %>% 
   #layout(boxmode = "group")
#p12 <- ggplotly(p12) %>% 
   #layout(boxmode = "group")

```
## *Mineralization Plots*

```{r, echo = FALSE,   fig.width=12, fig.height=5, warning = FALSE}
grid.arrange(p1, p3, p4, p7, p9, p10, nrow = 2)
```

## *Nitrification Plots*

```{r, echo = FALSE,   fig.width=12, fig.height=5, warning = FALSE}
grid.arrange(p2, p5, p6, p8, p11, p12, nrow = 2)
```

# Nitrogen cycling statistics 

```{r testing for normality and making graph of output, echo=FALSE, warning=FALSE}
# All net mineralization data
NetMin_Dist <- shapiro.test(N_cycling$Net_Mineralization) # not normal

# All net nitrification data
NetNit_Dist <- shapiro.test(N_cycling$Net_Nitrification) # not normal

#subset data to just Fall19
Fall19 <-subset(N_cycling, Season=="Fall19")

#subset data to just Spring20
Spring20 <- subset(N_cycling, Season=="Spring20")

# 2019 Net Mineralization  
Fall19_NetMin_Dist <- shapiro.test(Fall19$Net_Mineralization) #normal
Fall19_NetMin_Var_Site <- bartlett.test(Fall19$Net_Mineralization~Fall19$Site) # equal variance between sites
Fall19_NetMin_Var_Invasion <- bartlett.test(Fall19$Net_Mineralization~Fall19$Site) #equal variance between invasion

#2020 Net Mineralization 
Spring20_NetMin_Dist <- shapiro.test(Spring20$Net_Mineralization)#not normal 

#2019 Net Nitrification
Fall19_NetNit_Dist <- shapiro.test(Fall19$Net_Nitrification) #not normal

#2020 Net Nitrification
Spring20_NetNit_Dist <- shapiro.test(Spring20$Net_Nitrification) #not normal

#Making vectors for output graph
Data <- c('NetMin_Dist', 'NetNit_Dist', 'Fall19_NetMin_Dist', 'Spring20_NetMin_Dist', 'Fall19_NetNit_Dist', 'Spring20_NetNit_Dist')
p_value_normal_distribution <- c(NetMin_Dist$p.value, NetNit_Dist$p.value, Fall19_NetMin_Dist$p.value, Spring20_NetMin_Dist$p.value, Fall19_NetNit_Dist$p.value, Spring20_NetNit_Dist$p.value)

#Is there a way to add a third column "Normal distribution?" that says YES if p-value > 0.05 and NO if p-value < 0.05?

NormalDist <- data.frame(Data,p_value_normal_distribution)
NormalDist


```


```{r, Net Min and Net Nit significance between sites and invasion, echo=TRUE, warning=FALSE}

# All data Net Min versus Invasion significance 
wilcox.test(Net_Mineralization ~ Invasion, data = N_cycling) # no significant difference
kruskal.test(Net_Mineralization ~ Site, data = N_cycling) # no significant difference

# All data Net Nit versus Invasion significance
wilcox.test(Net_Nitrification ~ Invasion, data = N_cycling) # no significant difference
kruskal.test(Net_Nitrification ~ Site, data = N_cycling) # no significant difference

#Fall19 NetMin versus Invasion per site 
anova.Fall19.NetMin<- aov(Net_Mineralization ~ Invasion * Site, data = Fall19)
summary(anova.Fall19.NetMin)

#Spring20 Net Min versus Invasion
wilcox.test(Net_Mineralization ~ Invasion, data = Spring20) # no significant difference
kruskal.test(Net_Mineralization ~ Site, data = Spring20) # no significant difference

#Fall19 Net Nit versus invasion
wilcox.test(Net_Nitrification ~ Invasion, data = Fall19) # no significant difference
kruskal.test(Net_Nitrification ~ Site, data = Fall19) # no significant difference

#Spring20 Net Nit versus invasion
wilcox.test(Net_Nitrification ~ Invasion, data = Spring20) # no significant difference
kruskal.test(Net_Nitrification ~ Site, data = Spring20) # no significant difference


```

```{r C:N versus N cycling statistics, warning=FALSE}
#Add in separate regression lines for invaded and uninvaded 
lmC.NNetMin <- lm(Soil_CN ~ Net_Mineralization, data = N_cycling)
summary(lmC.NNetMin)

lm.C.NNetNit <- lm(Soil_CN ~ Net_Nitrification, data = N_cycling)
summary(lm.C.NNetNit)

Fall19lmC.NNetMin <- lm(Soil_CN ~ Net_Mineralization, data = Fall19)
summary(Fall19lmC.NNetMin)

Spring20lmC.NNetMin <- lm(Soil_CN ~ Net_Mineralization, data = Spring20)
summary(Spring20lmC.NNetMin)

Fall19lmC.NNetNit <- lm(Soil_CN ~ Net_Nitrification, data = Fall19)
summary(Fall19lmC.NNetNit)

Spring20lmC.NNetNit <- lm(Soil_CN ~ Net_Nitrification, data = Spring20)
summary(Spring20lmC.NNetNit)
```
# C:N versus nitrogen cycling figures
```{r, echo=FALSE, warning=FALSE}
p9 <- ggplot(N_cycling, aes(x=Net_Mineralization, y=Soil_CN, color=Invasion, shape=Invasion, label=Field_ID)) + geom_point() + ggtitle("All Data") + theme(plot.title = element_text(hjust = 0.5)) + geom_abline(slope = lmC.NNetMin$coefficients[2], intercept = lmC.NNetMin$coefficients[1]) +geom_smooth(method = "lm")

p10 <- ggplot(N_cycling, aes(x=Net_Nitrification, y=Soil_CN, color=Invasion, shape=Invasion, label=Field_ID)) + geom_point() + ggtitle("All Data") + theme(plot.title = element_text(hjust = 0.5)) + geom_abline(slope = lm.C.NNetNit$coefficients[2], intercept = lm.C.NNetNit$coefficients[1]) + geom_smooth(method = "lm")

p11 <- ggplot(Fall19, aes(x=Net_Mineralization, y=Soil_CN, color=Invasion, shape=Invasion, label = Field_ID)) + geom_point()+ ggtitle("Fall 2019") + theme(plot.title = element_text(hjust = 0.5)) + geom_abline(slope = Fall19lmC.NNetMin$coefficients[2], intercept = Fall19lmC.NNetMin$coefficients[1]) + geom_smooth(method = "lm")

p12 <- ggplot(Spring20, aes(Net_Mineralization, y=Soil_CN, color=Invasion, shape=Invasion, label = Field_ID)) + geom_point()+ ggtitle("Spring 2020") + theme(plot.title = element_text(hjust = 0.5)) + geom_abline(slope = Spring20lmC.NNetMin$coefficients[2], intercept = Spring20lmC.NNetMin$coefficients[1]) + geom_smooth(method = "lm")

p13 <- ggplot(Fall19, aes(x=Net_Nitrification, y=Soil_CN, color=Invasion, shape=Invasion, label = Field_ID)) + geom_point() + ggtitle("Fall 2019") + theme(plot.title = element_text(hjust = 0.5))  + geom_abline(slope = Fall19lmC.NNetNit$coefficients[2], intercept = Fall19lmC.NNetNit$coefficients[1]) + geom_smooth(method = "lm")

p14 <- ggplot(Spring20, aes(x=Net_Nitrification, y=Soil_CN, color=Invasion, shape=Invasion, label = Field_ID)) + geom_point() + ggtitle("Spring 2020") + theme(plot.title = element_text(hjust = 0.5)) + geom_abline(slope = Spring20lmC.NNetNit$coefficients[2], intercept = Spring20lmC.NNetNit$coefficients[1]) + geom_smooth(method = "lm")

ggplotly(p9)
ggplotly(p10)
ggplotly(p11)
ggplotly(p12)
ggplotly(p13)
ggplotly(p14)
```
```{r vegetation stats, Warning=FALSE}
#Test normality for 
Veg_CN_Dist <- shapiro.test(Spring20$Veg_CN) #normal distribution
Veg_Biomass_Dist <- shapiro.test(Spring20$Biomass_.g._per_m.2) #normal distribution

#test for equal variance
Veg_CN_Var <- bartlett.test(Veg_CN~Site, data = N_cycling) #not equal variance 
Veg_Biomass_Var <- bartlett.test(N_cycling$Biomass_.g._per_m.2~N_cycling$Site) #equal variance

#Significance for Veg C&N
wilcox.test(Veg_CN~Invasion, data = N_cycling) # no significant difference between invasion
kruskal.test(Veg_CN ~ Site, data = N_cycling) # significant difference between sites
dunnTest(Veg_CN~Site, data = N_cycling, method="bh") #Shanahan significantly different from Coyote and NCAR

#Significance for Veg biomass
wilcox.test(N_cycling$Biomass_.g._per_m.2~N_cycling$Invasion) # significant difference between invasion
kruskal.test(N_cycling$Biomass_.g._per_m.2 ~ N_cycling$Site) #no significant difference between sites

```

```{r vegetation, echo=FALSE, warning=FALSE}
#Veg C:N per site and invasion
p15 <- ggplot(data = N_cycling, mapping = aes(x = Site, y = Veg_CN, fill = Invasion, label=Field_ID)) + geom_boxplot() + ggtitle("Vegetation C:N") + theme(plot.title = element_text(hjust = 0.5)) + ylab("C:N")

#Veg biomass per site and invasion
p16 <- ggplot(data = N_cycling, mapping = aes(x = Site, y = N_cycling$Biomass_.g._per_m.2, fill = Invasion, label=Field_ID)) + geom_boxplot() + ggtitle("Vegetation Biomass") + theme(plot.title = element_text(hjust = 0.5)) + ylab("Biomass (g)")

#All Veg C:N
p17 <- ggplot(data = N_cycling, mapping = aes(x = Invasion, y = Veg_CN, label=Field_ID)) + geom_boxplot() + ggtitle("Vegetation C:N") + theme(plot.title = element_text(hjust = 0.5)) + ylab("C:N")

#all veg biomass
p18 <- ggplot(data = N_cycling, mapping = aes(x = Invasion, y = N_cycling$Biomass_.g._per_m.2, label=Field_ID)) + geom_boxplot() + ggtitle("Vegetation Biomass") + theme(plot.title = element_text(hjust = 0.5)) + ylab("Biomass (g)")


ggplotly(p15)%>% 
   layout(boxmode = "group")
ggplotly(p16)%>% 
   layout(boxmode = "group")
ggplotly(p17)%>% 
   layout(boxmode = "group")
ggplotly(p18)%>% 
   layout(boxmode = "group")
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
